controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    drob_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true
    
    drob_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    drob_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

drob_effort_controller:
  ros__parameters:
    joints:
      - lfj
      - rfj
      - lbj
      - rbj
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

drob_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["lbj", "lfj"]
    right_wheel_names: ["rbj", "rfj"]

    wheel_separation: 0.3
    wheel_radius: 0.05

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 3.0
    angular.z.min_velocity: -3.0
    
    linear.x.pid.p: 2.0
    linear.x.pid.i: 0.05
    linear.x.pid.d: 0.02
    linear.x.pid.i_clamp: 1.0
    
    angular.z.pid.p: 4.0
    angular.z.pid.i: 0.15
    angular.z.pid.d: 0.08
    angular.z.pid.i_clamp: 2.0
    
    linear.x.pid.antiwindup: true
    angular.z.pid.antiwindup: true
    
    linear.x.min_velocity_threshold: 0.01
    angular.z.min_velocity_threshold: 0.02
    
    angular.z.pid.min_velocity: 0.05
    angular.z.pid.max_velocity: 3.0 