controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    drob_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true
    
    # 四轮独立速度控制器 - 使用JointGroupVelocityController
    drob_left_front_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      use_sim_time: true
    
    drob_right_front_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      use_sim_time: true
    
    drob_left_back_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      use_sim_time: true
    
    drob_right_back_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      use_sim_time: true
    


# 左前轮速度控制器
drob_left_front_velocity_controller:
  ros__parameters:
    joints:
      - lfj
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      lfj:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        antiwindup: true

# 右前轮速度控制器
drob_right_front_velocity_controller:
  ros__parameters:
    joints:
      - rfj
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      rfj:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        antiwindup: true

# 左后轮速度控制器
drob_left_back_velocity_controller:
  ros__parameters:
    joints:
      - lbj
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      lbj:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        antiwindup: true

# 右后轮速度控制器
drob_right_back_velocity_controller:
  ros__parameters:
    joints:
      - rbj
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      rbj:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        antiwindup: true



# 左前轮位置控制器
drob_left_front_position_controller:
  ros__parameters:
    joints:
      - lfj
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      lfj:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        antiwindup: true

# 右前轮位置控制器
drob_right_front_position_controller:
  ros__parameters:
    joints:
      - rfj
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      rfj:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        antiwindup: true

# 左后轮位置控制器
drob_left_back_position_controller:
  ros__parameters:
    joints:
      - lbj
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      lbj:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        antiwindup: true

# 右后轮位置控制器
drob_right_back_position_controller:
  ros__parameters:
    joints:
      - rbj
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      rbj:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        antiwindup: true 