controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    drob_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true
    
    # 恢复前轮控制器
    drob_left_front_velocity_controller:
      type: forward_command_controller/ForwardCommandController
      use_sim_time: true
                
    drob_right_front_velocity_controller:
      type: forward_command_controller/ForwardCommandController
      use_sim_time: true
    
    drob_left_back_velocity_controller:
      type: forward_command_controller/ForwardCommandController
      use_sim_time: true
    
    drob_right_back_velocity_controller:
      type: forward_command_controller/ForwardCommandController
      use_sim_time: true


# 前轮控制器恢复
drob_left_front_velocity_controller:
  ros__parameters:
    joints:
      - lfj
    interface_name: velocity

drob_right_front_velocity_controller:
  ros__parameters:
    joints:
      - rfj
    interface_name: velocity

# 左后轮速度控制器 - 主驱动轮
drob_left_back_velocity_controller:
  ros__parameters:
    joints:
      - lbj
    interface_name: velocity

# 右后轮速度控制器 - 主驱动轮
drob_right_back_velocity_controller:
  ros__parameters:
    joints:
      - rbj
    interface_name: velocity